sonar.projectKey=personal-dividend-app
sonar.organization=personal

sonar.sources=dividendapp,accounts,dividends
sonar.tests=dividends/tests.py
sonar.language=py

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/migrations/**,**/staticfiles/**,manage.py
