# Generated by Django 4.2.30 on 2026-04-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.FloatField(help_text='1 EUR = <rate> <currency>')),
                ('asof', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-asof'],
                'indexes': [models.Index(fields=['currency', '-asof'], name='dividends_f_currenc_f5caea_idx')],
            },
        ),
    ]
